// 当前场景配置（原生小程序运行用）—— 这份是「高校食堂」
// 换场景：把 configs.js 里 takeout / drinks 那份的字段照搬过来即可（结构完全一致）。
module.exports = {
  theme: { mode: "light", accent: "#3aa676" },
  brand: "阳光大学 · 中心食堂",
  sub: "今日菜单 · 明厨亮灶",
  notice: "今日推荐：番茄牛腩、蒜蓉西兰花，11:00 开餐",
  dateMode: true,
  ordering: false,
  needAddress: false,
  categories: [
    { id: "all", name: "全部" },
    { id: "hot", name: "热菜" },
    { id: "veg", name: "素菜" },
    { id: "staple", name: "主食" },
    { id: "soup", name: "汤品" },
  ],
  dishes: [
    { id: "c1", cat: "hot", name: "番茄牛腩", price: 12, unit: "份", tags: ["招牌", "今日推荐"], rating: 4.8,
      thumb: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=70",
      desc: "牛腩慢炖入味，番茄汤汁浓郁，拌饭一绝。",
      reviews: [
        { name: "王**", stars: 5, text: "牛腩炖得很烂，汤汁拌饭绝了，希望天天有。", date: "06-25" },
        { name: "李**", stars: 4, text: "味道不错，就是有时去晚了就没了。", date: "06-24" },
      ] },
    { id: "c2", cat: "hot", name: "宫保鸡丁", price: 9, unit: "份", tags: ["微辣"], rating: 4.5, days: [1, 3, 5],
      thumb: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=400&q=70",
      desc: "鸡丁滑嫩，花生香脆，酸甜微辣下饭。",
      reviews: [{ name: "赵**", stars: 5, text: "花生很脆，鸡肉给得足。", date: "06-25" }] },
    { id: "c3", cat: "hot", name: "红烧排骨", price: 13, unit: "份", tags: ["人气"], rating: 4.7, days: [2, 4, 6],
      thumb: "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&q=70",
      desc: "肉质酥软，咸甜适口，连汤汁都想拌饭。",
      reviews: [{ name: "孙**", stars: 5, text: "排骨大块，性价比高。", date: "06-23" }] },
    { id: "c4", cat: "veg", name: "蒜蓉西兰花", price: 6, unit: "份", tags: ["清淡", "今日推荐"], rating: 4.6,
      thumb: "https://images.unsplash.com/photo-1583663848692-6f2c0e8d8e9d?w=400&q=70",
      desc: "西兰花脆嫩，蒜香清爽，少油少盐。",
      reviews: [{ name: "周**", stars: 4, text: "很新鲜，就是想再多给一点。", date: "06-24" }] },
    { id: "c5", cat: "veg", name: "麻婆豆腐", price: 7, unit: "份", tags: ["微辣"], rating: 4.4, days: [1, 2, 4, 5],
      thumb: "https://images.unsplash.com/photo-1582576163090-09d3b6f8e2b6?w=400&q=70",
      desc: "豆腐嫩滑，麻辣鲜香，经典川味。",
      reviews: [{ name: "吴**", stars: 4, text: "够麻够辣，下饭。", date: "06-22" }] },
    { id: "c6", cat: "staple", name: "扬州炒饭", price: 8, unit: "份", tags: [], rating: 4.3,
      thumb: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&q=70",
      desc: "粒粒分明，配料丰富，一份管饱。",
      reviews: [{ name: "郑**", stars: 4, text: "分量足，火腿肠有点少。", date: "06-21" }] },
    { id: "c7", cat: "staple", name: "牛肉拉面", price: 11, unit: "碗", tags: ["现做"], rating: 4.6, days: [1, 3, 5, 7],
      thumb: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=70",
      desc: "汤头清亮，面条筋道，现拉现煮。",
      reviews: [{ name: "冯**", stars: 5, text: "汤很鲜，牛肉片给得不少。", date: "06-25" }] },
    { id: "c8", cat: "soup", name: "紫菜蛋花汤", price: 3, unit: "份", tags: ["免费续"], rating: 4.5,
      thumb: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=70",
      desc: "蛋花细腻，清口解腻，可免费续汤。",
      reviews: [{ name: "陈**", stars: 5, text: "能续汤太贴心了。", date: "06-20" }] },
    { id: "c9", cat: "soup", name: "玉米排骨汤", price: 6, unit: "份", tags: ["养生"], rating: 4.7, days: [2, 4, 6],
      thumb: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&q=70",
      desc: "玉米清甜，排骨炖足两小时，汤色奶白。",
      reviews: [{ name: "褚**", stars: 5, text: "汤很浓，喝着舒服。", date: "06-19" }] },
  ],
  feedback: {
    title: "给食堂提建议",
    placeholder: "菜品口味、卫生、价格、排队…想说的都写给后勤吧",
    tags: ["希望多上新菜", "菜偏咸了", "排队时间长", "卫生很好", "希望延长开餐"],
  },
};
