// 当前社区配置（原生运行用）—— 这份是「同城社交」。
// 换社区：把 configs.js 里 kids / outdoor 那份照搬过来（结构一致）。
module.exports = {
  theme: { accent: "#19b36b" },
  brand: "享趣周边",
  city: "深圳",
  slogan: "找搭子，一起出发",
  banner: { title: "暑趣模式开启", sub: "周末别躺平 · 上车找搭子", color: "#19b36b" },
  categories: [
    { icon: "tent", name: "露营烧烤" }, { icon: "dice", name: "桌游剧本" }, { icon: "mountain", name: "徒步爬山" },
    { icon: "mic", name: "Livehouse" }, { icon: "frisbee", name: "运动局" }, { icon: "bowl", name: "饭搭子" },
    { icon: "camera", name: "City Walk" }, { icon: "party", name: "派对交友" },
  ],
  filters: ["全部", "活动派对", "户外", "同好交友", "运动"],
  activities: [
    { id: "c1", cat: "活动派对", title: "拒绝躺平！一场「撕名牌+躲猫猫」大作战", cover: "https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=600&q=70",
      tags: ["主题体验", "陌生人social"], organizer: { name: "婷婷", badge: "婷", views: 1086 },
      date: "06-26 周五", time: "19:00 - 21:30", place: "深圳北站 · 中心公园", distance: "10.66km", price: 38, capacity: 20, joined: 12,
      avatars: ["阿", "K", "丸", "蓉", "豆", "九", "冯", "陈", "周", "吴", "郑", "孙"],
      highlights: ["破冰小游戏，社恐友好", "撕名牌 + 躲猫猫双玩法", "赢家有神秘小奖品"],
      includes: ["场地与道具", "领队带队", "饮用水"], desc: "周五晚来释放一周压力！分队 PK，轻松认识新朋友，社恐也能玩开。迟到不等人，记得准时上车～" },
    { id: "c2", cat: "户外", title: "周末出逃计划 · 露营烧烤肉局", cover: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=70",
      tags: ["主题体验", "露营"], organizer: { name: "椰椰", badge: "椰", views: 916 },
      date: "06-27 周六", time: "15:30 - 22:30", place: "大学城 · 营地", distance: "14.5km", price: 128, capacity: 16, joined: 9,
      avatars: ["林", "M", "猫", "卡", "图", "九", "顾", "钱", "孙"],
      highlights: ["天幕 + 桌椅全配好", "无限畅吃烧烤食材", "草坪游戏 + 音响"],
      includes: ["营地与装备", "烧烤食材", "饮料"], desc: "把城市留在身后，草坪、天幕、烤串和音乐，朋友是现场认识的。带上好心情就行，装备我们全包。" },
    { id: "c3", cat: "同好交友", title: "桌游剧本之夜 · 微醺推理局", cover: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600&q=70",
      tags: ["桌游", "微醺"], organizer: { name: "阿楷", badge: "楷", views: 642 },
      date: "06-27 周六", time: "19:30 - 23:00", place: "南山 · 桌游吧", distance: "6.2km", price: 68, capacity: 12, joined: 7,
      avatars: ["丸", "T", "豆", "九", "冯", "陈", "周"],
      highlights: ["新手本 + 进阶本都有", "DM 带本不冷场", "一杯特调随本送"],
      includes: ["桌游/剧本", "DM 主持", "特调一杯"], desc: "不尬聊，靠游戏破冰。新手友好，DM 全程带节奏，散场常常一起约下一场。" },
    { id: "c4", cat: "运动", title: "周日晨间飞盘 · 新手友好局", cover: "https://images.unsplash.com/photo-1591491653056-4313c1b6c9bb?w=600&q=70",
      tags: ["飞盘", "运动social"], organizer: { name: "Leo", badge: "L", views: 503 },
      date: "06-28 周日", time: "09:00 - 11:00", place: "深圳湾 · 体育公园", distance: "8.1km", price: 45, capacity: 18, joined: 14,
      avatars: ["阿", "K", "蓉", "豆", "九", "冯", "陈", "周", "吴", "郑", "孙", "钱", "顾", "林"],
      highlights: ["专业教练教规则", "分队对抗不站桩", "运动 + 拍照两不误"],
      includes: ["飞盘与标志桶", "教练带队", "运动饮料"], desc: "零基础也能上手的飞盘局，跑起来认识新朋友。记得穿运动鞋，做好热身～" },
    { id: "c5", cat: "户外", title: "City Walk · 老街区咖啡漫游", cover: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=70",
      tags: ["City Walk", "摄影"], organizer: { name: "小鹿", badge: "鹿", views: 388 },
      date: "06-28 周日", time: "16:00 - 18:30", place: "蛇口 · 老街", distance: "9.3km", price: 30, capacity: 15, joined: 6,
      avatars: ["丸", "蓉", "豆", "九", "冯", "陈"],
      highlights: ["小众机位边走边拍", "两家宝藏咖啡馆", "出片率超高"],
      includes: ["领队讲解", "拍照指导"], desc: "慢下来逛逛老城区，咖啡香里聊聊天、拍拍照，适合一个人来认识同好。" },
    { id: "c6", cat: "活动派对", title: "周六夜 · 天台微醺音乐派对", cover: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=70",
      tags: ["派对", "音乐"], organizer: { name: "Mia", badge: "M", views: 1203 },
      date: "06-27 周六", time: "20:00 - 23:30", place: "福田 · 天台 Bar", distance: "5.0km", price: 88, capacity: 30, joined: 21,
      avatars: ["阿", "K", "丸", "蓉", "豆", "九", "冯", "陈", "周", "吴", "郑", "孙", "钱", "顾", "林", "猫", "图", "卡", "T", "九", "婷"],
      highlights: ["DJ 现场 + 天台夜景", "一杯欢迎特调", "社交游戏破冰"],
      includes: ["入场 + 一杯特调", "DJ/音响", "拍立得"], desc: "城市夜景 + 微醺 + 音乐，认识有趣的人。穿得好看点，今晚的主角是你。" },
  ],
};
